const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8');
const elements=new Map(),el=id=>{if(!elements.has(id))elements.set(id,{value:'',checked:false,type:'text',appendChild(){},addEventListener(){}});return elements.get(id);};
const context={document:{getElementById:el,createElement:()=>({})},localStorage:{getItem:()=>null,setItem(){}},console};vm.createContext(context);
vm.runInContext('const $=id=>document.getElementById(id);\n'+html.slice(html.indexOf('const RULES='),html.indexOf('const CAPLAB='))+`\nthis.E={buildCalendar,predict,ensurePlanifSessionIds,findPlanifSession,applyPlanifMoves,planifMoveCheck,parseDate,planDateKey};this.setActive=p=>activePlan=p;this.preserve=preservePastSessions;`,context);
const E=context.E;
const st={mode:'cal',calStart:'2026-10-05',calRace:'2026-12-20',calDist:1,calGoal:null,avail:[false,true,true,false,true,true,true],q1Day:'1',q2Day:'4',q3Day:'',slDay:'6',vma:17,s2:14,s1lo:11.5,s1hi:12,refDist:0,refTime:19*60+25,profile:1,penalty:false,ref2Dist:1,ref2Time:null,block:'spec',specDist:1,specGoal:null,N:4,vol:300,runs:5,qualityCount:2,assimQ2:false};
const build=()=>{const C=E.buildCalendar(st,E.predict(st));E.ensurePlanifSessionIds(C);return C;};
const C=build(),id='w0-q1',found=E.findPlanifSession(C,id);assert(found);const original=E.planDateKey(found.day.date),to='2026-10-08';
const before=JSON.stringify({vol:found.w.vol,load:found.w.load,quality:found.w.qualityMinutes,s:found.it.s});
const check=E.planifMoveCheck(C,id,to,st);assert(check.warnings.length,'moving to originally unavailable Thursday warns');
const moves={[id]:{from:original,to}};E.applyPlanifMoves(C,moves);assert.equal(E.planDateKey(E.findPlanifSession(C,id).day.date),to);assert(!found.day.items.some(x=>x.planifId===id));
assert.equal(JSON.stringify({vol:found.w.vol,load:found.w.load,quality:found.w.qualityMinutes,s:E.findPlanifSession(C,id).it.s}),before);
const saved=JSON.parse(JSON.stringify(C));context.setActive({plan:saved});const rebuilt=E.applyPlanifMoves(context.preserve(build()),moves,saved);
assert.equal(E.planDateKey(E.findPlanifSession(rebuilt,id).day.date),to);assert.equal(rebuilt.weeks.flatMap(w=>w.days.flatMap(d=>d.items)).filter(x=>x.planifId===id).length,1,'past snapshot + future generated source deduplicate');
E.applyPlanifMoves(rebuilt,{[id]:{from:original,to:original}},saved);assert.equal(E.planDateKey(E.findPlanifSession(rebuilt,id).day.date),original);
// Missing source in regenerated past days falls back to saved content, even for a future target.
const missing=build();for(const d of missing.weeks[0].days)d.items=d.items.filter(x=>x.planifId!==id);
E.applyPlanifMoves(missing,{[id]:{from:original,to:'2026-10-11'}},saved);assert.equal(E.planDateKey(E.findPlanifSession(missing,id).day.date),'2026-10-11');
assert.throws(()=>E.planifMoveCheck(C,id,'2026-10-12',st),/même semaine/);
const other=C.weeks[0].days.find(d=>d.items.some(x=>x.kind==='q'&&x.planifId!==id));assert(E.planifMoveCheck(C,id,E.planDateKey(other.date),st).warnings.some(x=>x.includes('déjà')));
const last=C.weeks.at(-1),rappel=last.days.flatMap(d=>d.items).find(x=>x.kind==='q'),race=last.days.flatMap(d=>d.items).find(x=>x.kind==='race');
assert.throws(()=>E.planifMoveCheck(C,rappel.planifId,'2026-12-18',st),/J−2/);
assert.throws(()=>E.planifMoveCheck(C,rappel.planifId,'2026-12-19',st),/J−3 ou J−4/);
assert.throws(()=>E.planifMoveCheck(C,race.planifId,'2026-12-19',st),/fixée/);
const near=build().weeks.at(-2),sl=near.days.flatMap(d=>d.items).find(x=>x.kind==='sl');assert(sl);near.sl=75;
const fixture={weeks:[near]};assert.throws(()=>E.planifMoveCheck(fixture,sl.planifId,'2026-12-13',st),/plafond/);
E.applyPlanifMoves(fixture,{[sl.planifId]:{to:'2026-12-13'}},null,st);assert(fixture.moveWarnings[sl.planifId].includes('plafond'),'replay rechecks long-run guard after recalculation');
assert(!html.includes('data-planif-move'));assert(!html.includes('data-planif-restore'));assert(html.includes('planifMoveNoticeHtml()'));
console.log('OK: move Friday to Thursday, stable ID/content/weekly totals, persistence after regeneration and past preservation, deduplication, restore, occupied-day warning, week boundary and taper/long-run guards.');
